name: Bug 回報（使用中文）
description: 識別錯誤、操作異常、連線錯誤等
labels: ["bug"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提問之前...
      description: |
        請確認自己完成了要求之後再進行勾選
      options:
        - label: 我理解 Issue 是用於回報和解決問題的，而非吐槽評論區，將盡可能提供更多資訊幫助問題解決
          required: true
        - label: 我填寫了簡短且清晰明確的標題，以便開發者在翻閱 Issue 列表時能快速確定大致問題。而不是「一個建議」、「卡住了」等
          required: true
        - label: 我使用的是目前更新版本的最新版，且已查看版本發布至今和 Pull Requests 中尚未發布的更新內容，並未提及該 Bug 已被修復的情況
          required: true
        - label: 我已檢查了置頂議題（Pinned Issue）（公告）、活躍議題（Open Issue）、已關閉議題（Closed Issue），確認我的問題未被提及
          required: true
  - type: textarea
    id: describe
    attributes:
      label: 問題描述
      description: 描述問題時請盡可能詳細
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: >-
        請提供 MXX 版本
      placeholder: |
        MXX Version:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日誌和設定檔
      description: |
        **請在關閉 MXX 後，上傳以下 3 個檔案：**
          1. `debug` 資料夾中的 `maa.log` `maa.bak.log` 日誌檔案，並說明問題出現的大致時間點
          2. `config` 資料夾中的 `maa_pi_config.json`(MaaPiCli) 設定檔

        如果你在使用 MacBook，請點擊螢幕左上角的「檔案」，點擊「開啟日誌資料夾」
        **請直接將完整的檔案拖曳進來，而非自己裁切或複製的片段；若檔案體積過大可壓縮後再上傳**
      placeholder: |
        請確認上傳檔案前已關閉 MXX
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: 設定資訊
      description: |
        請說明作業系統及版本、模擬器品牌、模擬器解析度、DPI、幀率；
        若正在使用 MuMu 12 或雷電 9，請說明截圖增強是否開啟；
        最後請說明 GPU 加速推理是否開啟，若開啟請提供 GPU 型號。
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 截圖或錄影
      description: |
        `debug` 目錄下按功能分類的資料夾內，有一些自動截圖的錯誤圖片，若有相關的，請一併打包上傳

        可上傳螢幕截圖或錄製以幫助解釋你的問題，包括但不限於 MXX 軟體截圖、遊戲畫面截圖、
        MXX debug 截圖（`debug/vision` 路徑圖片，在修改 `config/maa_option.json` 中 `save_draw` 為 `true` 後再次執行 MXX 取得）
        若是**識別相關問題**，請盡可能提供模擬器自帶的截圖工具截取的無遮擋的**原圖**（或透過 adb 截取原圖）
        用其他的工具（如QQ/微信）截取的圖片包含視窗邊框且長寬比、解析度不固定，不利於我們排除 bug
        若檔案體積過大可壓縮後再上傳
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 還有別的嗎？
      description: |
        任何能讓我們對你所遇到的問題有更多了解的東西
    validations:
      required: false
