name: 需求建議（使用中文）
description: 新功能、建議等
labels: ["enhancement"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提問之前...
      options:
        - label: 我填寫了簡短且清晰明確的標題，以便開發者在翻閱 Issue 列表時能快速確定大致問題。而不是「一個建議」、「卡住了」等
          required: true
        - label: 我基本確定這是一個新功能/建議，而不是遇到了 Bug（不確定的話請附上日誌）
          required: true
        - label: 我使用的是目前更新版本的最新版，且已查看版本發布至今和 Pull Requests 中尚未發布的更新內容，確認我的建議未被提及
          required: true
        - label: 我已檢查了置頂議題（Pinned Issue）（公告）、活躍議題（Open Issue）、已關閉議題（Closed Issue），確認我的建議未被提及
          required: true
  - type: textarea
    id: describe
    attributes:
      label: 說說你遇到的問題？
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: 有什麼好的想法？
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 其他內容
      description: 關於該需求建議的任何其他背景或螢幕截圖。
    validations:
      required: false
